<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="myWebForm.aspx.cs" Inherits="BRH_Plubic.myWebForm" %>

<!DOCTYPE html>
<html>
<head>
    <title>SignalR Simple Chat</title>
    <style type="text/css">
        .container {
            background-color: #99CCFF;
            border: thick solid #808080;
            padding: 20px;
            margin: 20px;
        }
    </style>
</head>
<body>
    <div class="col-12 mx-auto">
        <asp:Label ID="lbl_IPAddress" Text="" runat="server"></asp:Label>
    </div>
    <div class="container">
        FirstName <input type="text" id="txtfName" /> LastName <input type="text" id="txtlName" />
        <input type="button" id="btnSave" value="Save" />
    </div>

        <table width="50%" border="1" id="myTable">
        <!-- head table -->
        <thead>
          <tr>
            <td width="20%"> <div align="center">ID </div></td>
            <td width="20%"> <div align="center">DateTime </div></td>
            <td width="20%"> <div align="center">Department </div></td>
            <td width="20%"> <div align="center">FirstName </div></td>
            <td width="20%"> <div align="center">LastName </div></td>
          </tr>
        </thead>
        <!-- body dynamic rows -->
        <tbody></tbody>
        </table>
    <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="Scripts/jquery-3.4.1.min.js" "></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.4.1.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="/signalr/hubs"></script>
    <!--Add script to update the page and send messages.-->
    <script type="text/javascript">
        $(function () {


            // Declare a proxy to reference the hub.
            var chat = $.connection.myChatHub;

            // Create a function that the hub can call to broadcast messages.
            chat.client.displayData = function (jsonData) {

                $('#myTable > tbody:last').empty();

                var obj = jQuery.parseJSON(jsonData);
                $.each(obj, function (key, val) {
                    var id = val["id"];
                    var datetimes = val["datetimes"];
                    var dept = val["dept"];
                    var fname = val["fname"];
                    var lname = val["lname"];
                    var tr = "<tr>";
                    tr = tr + "<td>" + id + "</td>";
                    tr = tr + "<td>" + datetimes + "</td>";
                    tr = tr + "<td>" + dept + "</td>";
                    tr = tr + "<td>" + fname + "</td>";
                    tr = tr + "<td>" + lname + "</td>";
                    tr = tr + "</tr>";
                    $('#myTable > tbody:last').append(tr);
                });

            };


            // Start the connection.
            $.connection.hub.start().done(function () {
                $("#btnSave").click(function () {
                    var dept = '42';
                    // Call the Send method on the hub.
                    chat.server.callFunction("insert into mytable(IP, dept, fname, lname) values('" + $('<%= lbl_IPAddress.ClientID %>').val() + "','" + dept + "','" + $('#txtfName').val() + "','" + $('#txtlName').val() + "');", "");
                    // Clear text box and reset focus for next comment.
                    $("#txtName").val("").focus();
                    $("#txtEmail").val("").focus();
                });

                //First load
                //chat.server.callFunction("", "select * from mytable order by id;");
                
            });

        });
    </script>
</body>
</html>