<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="InputENRating.aspx.cs" Inherits="BRH_Plubic.GoodDoctor.InputENRating" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>BRH Good Doctor Register EN</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <!-- Main css -->
    <link href="../css/style.css" rel="stylesheet">

</head>
<body>
    <form id="form1" runat="server">
        <div>

            <div id="div_register" class="row col-12 mx-auto" runat="server" visible="true" style="position: absolute; top: 40%;">
                <div class="col-12 mx-auto text-center">
                    <input type="text" id="txt_en" value="" autofocus="autofocus" class="form-control" placeholder="กรุณากรอก EN" runat="server" />
                </div>
                <div class="col-12 mx-auto text-center">
                    <button id="btn_submit" class="btn btn-outline-primary" onserverclick="btn_submit_ServerClick" runat="server">Register</button>
                </div>
            </div>
            <div id="div_alert" runat="server" visible="false" style="position: fixed; bottom: 40%;">
                <asp:Label ID="lbl_alert" Text="" Font-Size="X-Large" runat="server"></asp:Label>
            </div>

        </div>
    </form>

    <!--Reference the jQuery library. -->
    <script src="../Scripts/jquery-3.4.1.min.js" "></script>
    <!--Reference the SignalR library. -->
    <script src="../Scripts/jquery.signalR-2.4.1.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="/signalr/hubs"></script>

    <script type="text/javascript">
        $(function () {


            // Declare a proxy to reference the hub.
            var chat = $.connection.centerHub;

            // Start the connection.
            $.connection.hub.start().done(function () {
                //First load
                chat.server.callFunction("", "select * from mytable order by id desc;");
            });

        });
    </script>

    <script>
        function CloseWindow(sec) {
            setTimeout(function () { window.close() }, sec*1000);
        }
    </script>

    <asp:Label ID="lbl_script" Text="" runat="server"></asp:Label>
</body>
</html>
