<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Generate.aspx.cs" Inherits="BRH_Plubic.Queue.Generate" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>

    <!--Reference the jQuery library. -->
    <script src="../Scripts/jquery-3.4.1.min.js" "></script>
    <!--Reference the SignalR library. -->
    <script src="../Scripts/jquery.signalR-2.4.1.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="/signalr/hubs"></script>

    <script type="text/javascript">
        $(function () {


            // Declare a proxy to reference the hub.
            var chat = $.connection.centerHub;

            // Start the connection.
            $.connection.hub.start().done(function () {
                //First load
                chat.server.callFunction("", "select * from mytable where convert(datetimes,date)=current_date order by id desc;");
                window.close();
            });

        });
    </script>

        </div>
    </form>
</body>
</html>
